### ISSUE TITLE
Enable issues?

### ISSUE THREAD

**Issue by g40** [EimaMei/Silicon#10]
@ColleagueRiley this is really for you.

Can you enable the issues tab for the silicon-h repository?

**Comment by ColleagueRiley** [comment]
@g40, Oh, I didn't know that was something I could do. I assume github didn't allow issues for forks or something.

Although, it doesn't really matter anymore. I don't know if you've seen but the official silicon repo has merged with silicon.h. So it doesn't really make any difference where to post issues anymore. I will say, though, I'm pretty sure, at the moment, Eima is less focused on Silicon at the moment and more focused on other projects.

**Comment by g40** [comment]
It still makes sense I think but it is entirely up to you. Just FYI, go to the repo settings and scroll down a bit:

![image](https://github.com/EimaMei/Silicon/assets/812250/5a5d7063-8bc4-488a-8e61-77f79965213c)

**Comment by ColleagueRiley** [comment]
@g40, I already enabled issues, thanks anyway.
