### ISSUE TITLE
Documentation for Silicon ?

### ISSUE THREAD

**Issue by 256colormode** [EimaMei/Silicon#15]
Can u please add a documentation for Silicon if u can?

**Comment by ColleagueRiley** [comment]
I'm pretty sure the apple cocoa documentation can be used for Silicon.h

**Comment by 256colormode** [comment]
ok i'll try

**Comment by EimaMei** [comment]
> Can u please add a documentation for Silicon if u can?

Hello. Could you please be more specific with what type of documentation is needed for you? Is it documentation for using Silicon, adding new methods and classes to Silicon, etc? Also the available documentation in the README.md is in the process of being rewritten, so in that regard it is being worked on.

**Comment by ColleagueRiley** [comment]
> I'm pretty sure the apple cocoa documentation can be used for Silicon.h

@mohanotfound  Yea, when I said this I was specifically referencing to Cocoa functions and objects. I don't know which part of Silicon you're asking for documentation for specifically.

**Comment by 256colormode** [comment]
> > I'm pretty sure the apple cocoa documentation can be used for Silicon.h
> 
> @mohanotfound Yea, when I said this I was specifically referencing to Cocoa functions and objects. I don't know which part of Silicon you're asking for documentation for specifically.

yeah ik

**Comment by EimaMei** [comment]
Closing this issue as of now since the author of it hasn't really specified the needed documentation at hand.
